# <font color=darkblue> Machine Learning model deployment with Flask framework</font>

## <font color=Blue>Used Cars Price Prediction Application</font>

### Objective:
1. To build a Machine learning regression model to predict the selling price of the used cars based on the different input features like fuel_type, kms_driven, type of transmission etc.
2. Deploy the machine learning model with the help of the flask framework.

### Dataset Information:
#### Dataset Source: https://www.kaggle.com/datasets/nehalbirla/vehicle-dataset-from-cardekho?select=CAR+DETAILS+FROM+CAR+DEKHO.csv
This dataset contains information about used cars listed on www.cardekho.com
- **Car_Name**: Name of the car
- **Year**: Year of Purchase
- **Selling Price (target)**: Selling price of the car in lakhs
- **Present Price**: Present price of the car in lakhs
- **Kms_Driven**: kilometers driven
- **Fuel_Type**: Petrol/diesel/CNG
- **Seller_Type**: Dealer or Indiviual
- **Transmission**: Manual or Automatic
- **Owner**: first, second or third owner


### 1. Import required libraries

In [41]:


import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score

import warnings

warnings.filterwarnings('ignore')

### 2. Load the dataset

In [42]:
df = pd.read_csv('C:/Users/niles/Downloads/cardata.csv')
df.head()

Car_Name  Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type  \
0     ritz  2014           3.35           5.59       27000    Petrol   
1      sx4  2013           4.75           9.54       43000    Diesel   
2     ciaz  2017           7.25           9.85        6900    Petrol   
3  wagon r  2011           2.85           4.15        5200    Petrol   
4    swift  2014           4.60           6.87       42450    Diesel   

  Seller_Type Transmission  Owner  
0      Dealer       Manual      0  
1      Dealer       Manual      0  
2      Dealer       Manual      0  
3      Dealer       Manual      0  
4      Dealer       Manual      0

### 3. Check the shape and basic information of the dataset.

In [43]:
df.shape

(301, 9)

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Car_Name       301 non-null    object 
 1   Year           301 non-null    int64  
 2   Selling_Price  301 non-null    float64
 3   Present_Price  301 non-null    float64
 4   Kms_Driven     301 non-null    int64  
 5   Fuel_Type      301 non-null    object 
 6   Seller_Type    301 non-null    object 
 7   Transmission   301 non-null    object 
 8   Owner          301 non-null    int64  
dtypes: float64(2), int64(3), object(4)
memory usage: 21.3+ KB


### 4. Check for the presence of the duplicate records in the dataset? If present drop them

In [45]:
len(df[df.duplicated()])

2

In [46]:
df.drop_duplicates(inplace=True)

In [47]:
len(df[df.duplicated()])

0

### 5. Drop the columns which you think redundant for the analysis.

In [48]:
df.drop('Car_Name',axis=1,inplace=True)

### 6. Extract a new feature called 'age_of_the_car' from the feature 'year' and drop the feature year

In [49]:
df['age_of_the_car'] = 2022 - df['Year']

In [50]:
df.drop('Year',axis=1,inplace=True)

In [51]:
df.head(2)

Selling_Price  Present_Price  Kms_Driven Fuel_Type Seller_Type  \
0           3.35           5.59       27000    Petrol      Dealer   
1           4.75           9.54       43000    Diesel      Dealer   

  Transmission  Owner  age_of_the_car  
0       Manual      0               8  
1       Manual      0               9

### 7. Encode the categorical columns

In [52]:
df['Fuel_Type'].unique()

array(['Petrol', 'Diesel', 'CNG'], dtype=object)

In [53]:
df['Seller_Type'].unique()

array(['Dealer', 'Individual'], dtype=object)

In [54]:
df['Fuel_Type'] = df['Fuel_Type'].replace({'Petrol':0, 'Diesel':1, 'CNG':2})

df['Seller_Type'] = df['Seller_Type'].replace({'Dealer':0, 'Individual':1})

df['Transmission'] = df['Transmission'].replace({'Manual':0, 'Automatic':1})

In [55]:
df['Fuel_Type'].unique()

array([0, 1, 2], dtype=int64)

In [56]:
df['Seller_Type'].unique()

array([0, 1], dtype=int64)

In [57]:
df['Transmission'].unique()

array([0, 1], dtype=int64)

In [58]:
df.head(2)

Selling_Price  Present_Price  Kms_Driven  Fuel_Type  Seller_Type  \
0           3.35           5.59       27000          0            0   
1           4.75           9.54       43000          1            0   

   Transmission  Owner  age_of_the_car  
0             0      0               8  
1             0      0               9

In [19]:
df['Transmission'].unique()

array(['Manual', 'Automatic'], dtype=object)

### 8. Separate the target and independent features.

In [59]:
X = df.drop('Selling_Price',axis=1)
y = df['Selling_Price']

### 9. Split the data into train and test.

In [60]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=0)

print(X_train.shape,X_test.shape)
print(y_train.shape,y_test.shape)

(209, 7) (90, 7)
(209,) (90,)


### 10. Build a Random forest Regressor model and check the r2-score for train and test.

In [61]:
rf = RandomForestRegressor()
rf.fit(X_train,y_train)

RandomForestRegressor()

In [63]:
y_train_pred = rf.predict(X_train)
y_test_pred = rf.predict(X_test)

r2_train = r2_score(y_train,y_train_pred)
r2_test = r2_score(y_test,y_test_pred)

print('r2-score train:',r2_train)
print('r2-score test',r2_test)

r2-score train: 0.9756975110413536
r2-score test 0.9024778800218459


### 11. Create a pickle file with an extension as .pkl

In [68]:
import pickle


rf = ...  

file_path = 'C:/Users/niles/Downloads/model.pkl'

with open(file_path, 'wb') as file:
    pickle.dump(rf, file)

### 12. Create new folder/new project in visual studio/pycharm that should contain the "model.pkl" file *make sure you are using a virutal environment and install required packages.*

### a) Create a basic HTML form for the frontend

Create a file **index.html** in the templates folder and copy the following code.

In [2]:
from IPython.display import display, HTML

html_code = '''
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Used Car Price Predictor</title>
    <style>
        body {
            background-color: #f0f0f0;
            font-family: Arial, sans-serif;
        }

        .header {
            background-image: linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url('background.jpg');
            background-size: cover;
            background-position: center;
            color: white;
            text-align: center;
            padding: 100px 0;
        }

        .form-container {
            background-color: #fff;
            border-radius: 10px;
            padding: 20px;
            max-width: 600px;
            margin: 50px auto;
            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
        }

        input, select {
            width: 100%;
            padding: 10px;
            margin-bottom: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
            font-size: 16px;
        }

        button {
            background-color: #007bff;
            color: #fff;
            border: none;
            padding: 10px 20px;
            border-radius: 5px;
            font-size: 16px;
            cursor: pointer;
        }

        button:hover {
            background-color: #0056b3;
        }
    </style>
</head>

<body>

    <div class="header">
        <h1>Used Car Price Predictor</h1>
        <h3><span id="prediction_text"></span></h3>
    </div>

    <div class="form-container">
        <form action="{{ url_for('predict')}}" method="post">
            <h2>Enter Car Details:</h2>
            <label for="age">Age of the car (In years)</label>
            <input id="age" name="Age_of_the_car" type="number" required>

            <label for="price">Present Showroom Price (In lakhs)</label>
            <input id="price" name="Present_Price" type="number" step="0.01" required>

            <label for="kms">Kilometers Driven</label>
            <input id="kms" name="Kms_Driven" type="number" required>

            <label for="owner">Owner Type (0/1/3)</label>
            <input id="owner" name="Owner" type="number" step="1" required>
            
            <label for="fuel">Fuel Type</label>
            <select name="Fuel_Type" id="fuel" required>
                <option value="0">Petrol</option>
                <option value="1">Diesel</option>
                <option value="2">CNG</option>
            </select>

            <label for="seller">Seller Type</label>
            <select name="Seller_Type" id="seller" required>
                <option value="0">Dealer</option>
                <option value="1">Individual</option>
            </select>

            <label for="transmission">Transmission Type</label>
            <select name="Transmission" id="transmission" required>
                <option value="0">Manual Car</option>
                <option value="1">Automatic Car</option>
            </select>
            
            <br><br>
            <button type="submit">Predict Selling Price</button>
        </form>
    </div>

</body>

</html>
'''

with open('index.html', 'w') as file:
    file.write(html_code)

print("index.html created successfully.")


index.html created successfully.


### b) Create app.py file and write the predict function

In [ ]:
from flask import Flask, render_template, request, jsonify
import pickle
import numpy as np
import sklearn


app = Flask(__name__)
model = pickle.load(open('C:/Users/niles/Downloads/model.pkl', 'rb'))


@app.route('/',methods=['GET'])
def Home():
    return render_template('index.html')


@app.route("/predict", methods=['POST'])
def predict():
    if request.method == 'POST':
        Present_Price=float(request.form['price'])
        Kms_Driven=int(request.form['kms'])
        Owner=int(request.form['owner'])
        Fuel_Type=request.form['fuel']
        Age_of_the_car=request.form['age']
        Seller_Type=request.form['seller']
        Transmission=request.form['transmission']

        prediction=model.predict([[Present_Price,Kms_Driven,Owner,Age_of_the_car,Fuel_Type,Seller_Type,Transmission]])
        output=round(prediction[0],2)
        return render_template('index.html',prediction_text="You can sell your car at {} lakhs".format(output))

if __name__=="__main__":
    app.run(debug=True)

### 13. Run the app.py python file which will render to index html page then enter the input values and get the prediction.

### Happy Learning :)